/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.parser;

import card.node.*;
import card.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTKeywordClass(@SuppressWarnings("unused") TKeywordClass node)
    {
        this.index = 0;
    }

    @Override
    public void caseTKeywordAddpattern(@SuppressWarnings("unused") TKeywordAddpattern node)
    {
        this.index = 1;
    }

    @Override
    public void caseTKeywordSame(@SuppressWarnings("unused") TKeywordSame node)
    {
        this.index = 2;
    }

    @Override
    public void caseTKeywordStraight(@SuppressWarnings("unused") TKeywordStraight node)
    {
        this.index = 3;
    }

    @Override
    public void caseTKeywordFlush(@SuppressWarnings("unused") TKeywordFlush node)
    {
        this.index = 4;
    }

    @Override
    public void caseTKeywordConfig(@SuppressWarnings("unused") TKeywordConfig node)
    {
        this.index = 5;
    }

    @Override
    public void caseTKeywordWin(@SuppressWarnings("unused") TKeywordWin node)
    {
        this.index = 6;
    }

    @Override
    public void caseTKeywordSystem(@SuppressWarnings("unused") TKeywordSystem node)
    {
        this.index = 7;
    }

    @Override
    public void caseTKeywordSelfreplace(@SuppressWarnings("unused") TKeywordSelfreplace node)
    {
        this.index = 8;
    }

    @Override
    public void caseTKeywordNext(@SuppressWarnings("unused") TKeywordNext node)
    {
        this.index = 9;
    }

    @Override
    public void caseTKeywordDefaultstatus(@SuppressWarnings("unused") TKeywordDefaultstatus node)
    {
        this.index = 10;
    }

    @Override
    public void caseTKeywordRank(@SuppressWarnings("unused") TKeywordRank node)
    {
        this.index = 11;
    }

    @Override
    public void caseTKeywordInitcard(@SuppressWarnings("unused") TKeywordInitcard node)
    {
        this.index = 12;
    }

    @Override
    public void caseTKeywordGetstatus(@SuppressWarnings("unused") TKeywordGetstatus node)
    {
        this.index = 13;
    }

    @Override
    public void caseTKeywordIsvalidcombination(@SuppressWarnings("unused") TKeywordIsvalidcombination node)
    {
        this.index = 14;
    }

    @Override
    public void caseTKeywordIswinnerfound(@SuppressWarnings("unused") TKeywordIswinnerfound node)
    {
        this.index = 15;
    }

    @Override
    public void caseTKeywordNextturn(@SuppressWarnings("unused") TKeywordNextturn node)
    {
        this.index = 16;
    }

    @Override
    public void caseTKeywordBefore(@SuppressWarnings("unused") TKeywordBefore node)
    {
        this.index = 17;
    }

    @Override
    public void caseTKerwordAfter(@SuppressWarnings("unused") TKerwordAfter node)
    {
        this.index = 18;
    }

    @Override
    public void caseTFuncDrawto(@SuppressWarnings("unused") TFuncDrawto node)
    {
        this.index = 19;
    }

    @Override
    public void caseTFuncDrawtoall(@SuppressWarnings("unused") TFuncDrawtoall node)
    {
        this.index = 20;
    }

    @Override
    public void caseTFuncSetcurplayerid(@SuppressWarnings("unused") TFuncSetcurplayerid node)
    {
        this.index = 21;
    }

    @Override
    public void caseTFuncSetdisplaysize(@SuppressWarnings("unused") TFuncSetdisplaysize node)
    {
        this.index = 22;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 23;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 24;
    }

    @Override
    public void caseTOpSemi(@SuppressWarnings("unused") TOpSemi node)
    {
        this.index = 25;
    }

    @Override
    public void caseTOpComma(@SuppressWarnings("unused") TOpComma node)
    {
        this.index = 26;
    }

    @Override
    public void caseTOpColon(@SuppressWarnings("unused") TOpColon node)
    {
        this.index = 27;
    }

    @Override
    public void caseTOpPlus(@SuppressWarnings("unused") TOpPlus node)
    {
        this.index = 28;
    }

    @Override
    public void caseTOpMinus(@SuppressWarnings("unused") TOpMinus node)
    {
        this.index = 29;
    }

    @Override
    public void caseTOpEqual(@SuppressWarnings("unused") TOpEqual node)
    {
        this.index = 30;
    }

    @Override
    public void caseTOpSuit(@SuppressWarnings("unused") TOpSuit node)
    {
        this.index = 31;
    }

    @Override
    public void caseTOpLeftSm(@SuppressWarnings("unused") TOpLeftSm node)
    {
        this.index = 32;
    }

    @Override
    public void caseTOpRightSm(@SuppressWarnings("unused") TOpRightSm node)
    {
        this.index = 33;
    }

    @Override
    public void caseTOpLeftMi(@SuppressWarnings("unused") TOpLeftMi node)
    {
        this.index = 34;
    }

    @Override
    public void caseTOpRightMi(@SuppressWarnings("unused") TOpRightMi node)
    {
        this.index = 35;
    }

    @Override
    public void caseTOpLeftLg(@SuppressWarnings("unused") TOpLeftLg node)
    {
        this.index = 36;
    }

    @Override
    public void caseTOpRightLg(@SuppressWarnings("unused") TOpRightLg node)
    {
        this.index = 37;
    }

    @Override
    public void caseTStringLiteral(@SuppressWarnings("unused") TStringLiteral node)
    {
        this.index = 38;
    }

    @Override
    public void caseTJavaLiteral(@SuppressWarnings("unused") TJavaLiteral node)
    {
        this.index = 39;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 40;
    }
}
