/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class AAfterValidStmt extends PValidStmt
{
    private PAfterStmt _afterStmt_;

    public AAfterValidStmt()
    {
        // Constructor
    }

    public AAfterValidStmt(
        @SuppressWarnings("hiding") PAfterStmt _afterStmt_)
    {
        // Constructor
        setAfterStmt(_afterStmt_);

    }

    @Override
    public Object clone()
    {
        return new AAfterValidStmt(
            cloneNode(this._afterStmt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAfterValidStmt(this);
    }

    public PAfterStmt getAfterStmt()
    {
        return this._afterStmt_;
    }

    public void setAfterStmt(PAfterStmt node)
    {
        if(this._afterStmt_ != null)
        {
            this._afterStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._afterStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._afterStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._afterStmt_ == child)
        {
            this._afterStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._afterStmt_ == oldChild)
        {
            setAfterStmt((PAfterStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
