/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class ADefaultstatusConfigKeyword extends PConfigKeyword
{
    private TKeywordDefaultstatus _keywordDefaultstatus_;

    public ADefaultstatusConfigKeyword()
    {
        // Constructor
    }

    public ADefaultstatusConfigKeyword(
        @SuppressWarnings("hiding") TKeywordDefaultstatus _keywordDefaultstatus_)
    {
        // Constructor
        setKeywordDefaultstatus(_keywordDefaultstatus_);

    }

    @Override
    public Object clone()
    {
        return new ADefaultstatusConfigKeyword(
            cloneNode(this._keywordDefaultstatus_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefaultstatusConfigKeyword(this);
    }

    public TKeywordDefaultstatus getKeywordDefaultstatus()
    {
        return this._keywordDefaultstatus_;
    }

    public void setKeywordDefaultstatus(TKeywordDefaultstatus node)
    {
        if(this._keywordDefaultstatus_ != null)
        {
            this._keywordDefaultstatus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordDefaultstatus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordDefaultstatus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordDefaultstatus_ == child)
        {
            this._keywordDefaultstatus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordDefaultstatus_ == oldChild)
        {
            setKeywordDefaultstatus((TKeywordDefaultstatus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
