/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class ADrawtoFuncKeyword extends PFuncKeyword
{
    private TFuncDrawto _funcDrawto_;

    public ADrawtoFuncKeyword()
    {
        // Constructor
    }

    public ADrawtoFuncKeyword(
        @SuppressWarnings("hiding") TFuncDrawto _funcDrawto_)
    {
        // Constructor
        setFuncDrawto(_funcDrawto_);

    }

    @Override
    public Object clone()
    {
        return new ADrawtoFuncKeyword(
            cloneNode(this._funcDrawto_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADrawtoFuncKeyword(this);
    }

    public TFuncDrawto getFuncDrawto()
    {
        return this._funcDrawto_;
    }

    public void setFuncDrawto(TFuncDrawto node)
    {
        if(this._funcDrawto_ != null)
        {
            this._funcDrawto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcDrawto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funcDrawto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funcDrawto_ == child)
        {
            this._funcDrawto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._funcDrawto_ == oldChild)
        {
            setFuncDrawto((TFuncDrawto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
