/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class ADrawtoallFuncKeyword extends PFuncKeyword
{
    private TFuncDrawtoall _funcDrawtoall_;

    public ADrawtoallFuncKeyword()
    {
        // Constructor
    }

    public ADrawtoallFuncKeyword(
        @SuppressWarnings("hiding") TFuncDrawtoall _funcDrawtoall_)
    {
        // Constructor
        setFuncDrawtoall(_funcDrawtoall_);

    }

    @Override
    public Object clone()
    {
        return new ADrawtoallFuncKeyword(
            cloneNode(this._funcDrawtoall_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADrawtoallFuncKeyword(this);
    }

    public TFuncDrawtoall getFuncDrawtoall()
    {
        return this._funcDrawtoall_;
    }

    public void setFuncDrawtoall(TFuncDrawtoall node)
    {
        if(this._funcDrawtoall_ != null)
        {
            this._funcDrawtoall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcDrawtoall_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funcDrawtoall_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funcDrawtoall_ == child)
        {
            this._funcDrawtoall_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._funcDrawtoall_ == oldChild)
        {
            setFuncDrawtoall((TFuncDrawtoall) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
