/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyFuncParaRest extends PFuncParaRest
{

    public AEmptyFuncParaRest()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyFuncParaRest();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyFuncParaRest(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
