/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class AEqualCompareRule extends PCompareRule
{
    private TOpEqual _opEqual_;

    public AEqualCompareRule()
    {
        // Constructor
    }

    public AEqualCompareRule(
        @SuppressWarnings("hiding") TOpEqual _opEqual_)
    {
        // Constructor
        setOpEqual(_opEqual_);

    }

    @Override
    public Object clone()
    {
        return new AEqualCompareRule(
            cloneNode(this._opEqual_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualCompareRule(this);
    }

    public TOpEqual getOpEqual()
    {
        return this._opEqual_;
    }

    public void setOpEqual(TOpEqual node)
    {
        if(this._opEqual_ != null)
        {
            this._opEqual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opEqual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opEqual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opEqual_ == child)
        {
            this._opEqual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opEqual_ == oldChild)
        {
            setOpEqual((TOpEqual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
