/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class AInitCard extends PInitCard
{
    private TKeywordInitcard _keywordInitcard_;
    private TOpLeftSm _opLeftSm_;
    private PInitPlayer _initPlayer_;
    private TOpRightSm _opRightSm_;
    private TOpLeftLg _opLeftLg_;
    private PInitCardStmt _initCardStmt_;
    private TOpRightLg _opRightLg_;

    public AInitCard()
    {
        // Constructor
    }

    public AInitCard(
        @SuppressWarnings("hiding") TKeywordInitcard _keywordInitcard_,
        @SuppressWarnings("hiding") TOpLeftSm _opLeftSm_,
        @SuppressWarnings("hiding") PInitPlayer _initPlayer_,
        @SuppressWarnings("hiding") TOpRightSm _opRightSm_,
        @SuppressWarnings("hiding") TOpLeftLg _opLeftLg_,
        @SuppressWarnings("hiding") PInitCardStmt _initCardStmt_,
        @SuppressWarnings("hiding") TOpRightLg _opRightLg_)
    {
        // Constructor
        setKeywordInitcard(_keywordInitcard_);

        setOpLeftSm(_opLeftSm_);

        setInitPlayer(_initPlayer_);

        setOpRightSm(_opRightSm_);

        setOpLeftLg(_opLeftLg_);

        setInitCardStmt(_initCardStmt_);

        setOpRightLg(_opRightLg_);

    }

    @Override
    public Object clone()
    {
        return new AInitCard(
            cloneNode(this._keywordInitcard_),
            cloneNode(this._opLeftSm_),
            cloneNode(this._initPlayer_),
            cloneNode(this._opRightSm_),
            cloneNode(this._opLeftLg_),
            cloneNode(this._initCardStmt_),
            cloneNode(this._opRightLg_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInitCard(this);
    }

    public TKeywordInitcard getKeywordInitcard()
    {
        return this._keywordInitcard_;
    }

    public void setKeywordInitcard(TKeywordInitcard node)
    {
        if(this._keywordInitcard_ != null)
        {
            this._keywordInitcard_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordInitcard_ = node;
    }

    public TOpLeftSm getOpLeftSm()
    {
        return this._opLeftSm_;
    }

    public void setOpLeftSm(TOpLeftSm node)
    {
        if(this._opLeftSm_ != null)
        {
            this._opLeftSm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opLeftSm_ = node;
    }

    public PInitPlayer getInitPlayer()
    {
        return this._initPlayer_;
    }

    public void setInitPlayer(PInitPlayer node)
    {
        if(this._initPlayer_ != null)
        {
            this._initPlayer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._initPlayer_ = node;
    }

    public TOpRightSm getOpRightSm()
    {
        return this._opRightSm_;
    }

    public void setOpRightSm(TOpRightSm node)
    {
        if(this._opRightSm_ != null)
        {
            this._opRightSm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opRightSm_ = node;
    }

    public TOpLeftLg getOpLeftLg()
    {
        return this._opLeftLg_;
    }

    public void setOpLeftLg(TOpLeftLg node)
    {
        if(this._opLeftLg_ != null)
        {
            this._opLeftLg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opLeftLg_ = node;
    }

    public PInitCardStmt getInitCardStmt()
    {
        return this._initCardStmt_;
    }

    public void setInitCardStmt(PInitCardStmt node)
    {
        if(this._initCardStmt_ != null)
        {
            this._initCardStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._initCardStmt_ = node;
    }

    public TOpRightLg getOpRightLg()
    {
        return this._opRightLg_;
    }

    public void setOpRightLg(TOpRightLg node)
    {
        if(this._opRightLg_ != null)
        {
            this._opRightLg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opRightLg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordInitcard_)
            + toString(this._opLeftSm_)
            + toString(this._initPlayer_)
            + toString(this._opRightSm_)
            + toString(this._opLeftLg_)
            + toString(this._initCardStmt_)
            + toString(this._opRightLg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordInitcard_ == child)
        {
            this._keywordInitcard_ = null;
            return;
        }

        if(this._opLeftSm_ == child)
        {
            this._opLeftSm_ = null;
            return;
        }

        if(this._initPlayer_ == child)
        {
            this._initPlayer_ = null;
            return;
        }

        if(this._opRightSm_ == child)
        {
            this._opRightSm_ = null;
            return;
        }

        if(this._opLeftLg_ == child)
        {
            this._opLeftLg_ = null;
            return;
        }

        if(this._initCardStmt_ == child)
        {
            this._initCardStmt_ = null;
            return;
        }

        if(this._opRightLg_ == child)
        {
            this._opRightLg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordInitcard_ == oldChild)
        {
            setKeywordInitcard((TKeywordInitcard) newChild);
            return;
        }

        if(this._opLeftSm_ == oldChild)
        {
            setOpLeftSm((TOpLeftSm) newChild);
            return;
        }

        if(this._initPlayer_ == oldChild)
        {
            setInitPlayer((PInitPlayer) newChild);
            return;
        }

        if(this._opRightSm_ == oldChild)
        {
            setOpRightSm((TOpRightSm) newChild);
            return;
        }

        if(this._opLeftLg_ == oldChild)
        {
            setOpLeftLg((TOpLeftLg) newChild);
            return;
        }

        if(this._initCardStmt_ == oldChild)
        {
            setInitCardStmt((PInitCardStmt) newChild);
            return;
        }

        if(this._opRightLg_ == oldChild)
        {
            setOpRightLg((TOpRightLg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
