/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class AInitStmt extends PInitStmt
{
    private PFuncStmt _funcStmt_;

    public AInitStmt()
    {
        // Constructor
    }

    public AInitStmt(
        @SuppressWarnings("hiding") PFuncStmt _funcStmt_)
    {
        // Constructor
        setFuncStmt(_funcStmt_);

    }

    @Override
    public Object clone()
    {
        return new AInitStmt(
            cloneNode(this._funcStmt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInitStmt(this);
    }

    public PFuncStmt getFuncStmt()
    {
        return this._funcStmt_;
    }

    public void setFuncStmt(PFuncStmt node)
    {
        if(this._funcStmt_ != null)
        {
            this._funcStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._funcStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._funcStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._funcStmt_ == child)
        {
            this._funcStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._funcStmt_ == oldChild)
        {
            setFuncStmt((PFuncStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
