/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class AMultiCompareRest extends PCompareRest
{
    private TOpComma _opComma_;
    private PCompareRule _compareRule_;
    private PCompareRest _compareRest_;

    public AMultiCompareRest()
    {
        // Constructor
    }

    public AMultiCompareRest(
        @SuppressWarnings("hiding") TOpComma _opComma_,
        @SuppressWarnings("hiding") PCompareRule _compareRule_,
        @SuppressWarnings("hiding") PCompareRest _compareRest_)
    {
        // Constructor
        setOpComma(_opComma_);

        setCompareRule(_compareRule_);

        setCompareRest(_compareRest_);

    }

    @Override
    public Object clone()
    {
        return new AMultiCompareRest(
            cloneNode(this._opComma_),
            cloneNode(this._compareRule_),
            cloneNode(this._compareRest_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiCompareRest(this);
    }

    public TOpComma getOpComma()
    {
        return this._opComma_;
    }

    public void setOpComma(TOpComma node)
    {
        if(this._opComma_ != null)
        {
            this._opComma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opComma_ = node;
    }

    public PCompareRule getCompareRule()
    {
        return this._compareRule_;
    }

    public void setCompareRule(PCompareRule node)
    {
        if(this._compareRule_ != null)
        {
            this._compareRule_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compareRule_ = node;
    }

    public PCompareRest getCompareRest()
    {
        return this._compareRest_;
    }

    public void setCompareRest(PCompareRest node)
    {
        if(this._compareRest_ != null)
        {
            this._compareRest_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compareRest_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opComma_)
            + toString(this._compareRule_)
            + toString(this._compareRest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opComma_ == child)
        {
            this._opComma_ = null;
            return;
        }

        if(this._compareRule_ == child)
        {
            this._compareRule_ = null;
            return;
        }

        if(this._compareRest_ == child)
        {
            this._compareRest_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opComma_ == oldChild)
        {
            setOpComma((TOpComma) newChild);
            return;
        }

        if(this._compareRule_ == oldChild)
        {
            setCompareRule((PCompareRule) newChild);
            return;
        }

        if(this._compareRest_ == oldChild)
        {
            setCompareRest((PCompareRest) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
