/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class APatternDeclareOver extends PPatternDeclareOver
{
    private TOpLeftSm _opLeftSm_;
    private PPatternOverRule _patternOverRule_;
    private TOpRightSm _opRightSm_;
    private TOpSemi _opSemi_;

    public APatternDeclareOver()
    {
        // Constructor
    }

    public APatternDeclareOver(
        @SuppressWarnings("hiding") TOpLeftSm _opLeftSm_,
        @SuppressWarnings("hiding") PPatternOverRule _patternOverRule_,
        @SuppressWarnings("hiding") TOpRightSm _opRightSm_,
        @SuppressWarnings("hiding") TOpSemi _opSemi_)
    {
        // Constructor
        setOpLeftSm(_opLeftSm_);

        setPatternOverRule(_patternOverRule_);

        setOpRightSm(_opRightSm_);

        setOpSemi(_opSemi_);

    }

    @Override
    public Object clone()
    {
        return new APatternDeclareOver(
            cloneNode(this._opLeftSm_),
            cloneNode(this._patternOverRule_),
            cloneNode(this._opRightSm_),
            cloneNode(this._opSemi_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPatternDeclareOver(this);
    }

    public TOpLeftSm getOpLeftSm()
    {
        return this._opLeftSm_;
    }

    public void setOpLeftSm(TOpLeftSm node)
    {
        if(this._opLeftSm_ != null)
        {
            this._opLeftSm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opLeftSm_ = node;
    }

    public PPatternOverRule getPatternOverRule()
    {
        return this._patternOverRule_;
    }

    public void setPatternOverRule(PPatternOverRule node)
    {
        if(this._patternOverRule_ != null)
        {
            this._patternOverRule_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._patternOverRule_ = node;
    }

    public TOpRightSm getOpRightSm()
    {
        return this._opRightSm_;
    }

    public void setOpRightSm(TOpRightSm node)
    {
        if(this._opRightSm_ != null)
        {
            this._opRightSm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opRightSm_ = node;
    }

    public TOpSemi getOpSemi()
    {
        return this._opSemi_;
    }

    public void setOpSemi(TOpSemi node)
    {
        if(this._opSemi_ != null)
        {
            this._opSemi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opSemi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opLeftSm_)
            + toString(this._patternOverRule_)
            + toString(this._opRightSm_)
            + toString(this._opSemi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opLeftSm_ == child)
        {
            this._opLeftSm_ = null;
            return;
        }

        if(this._patternOverRule_ == child)
        {
            this._patternOverRule_ = null;
            return;
        }

        if(this._opRightSm_ == child)
        {
            this._opRightSm_ = null;
            return;
        }

        if(this._opSemi_ == child)
        {
            this._opSemi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opLeftSm_ == oldChild)
        {
            setOpLeftSm((TOpLeftSm) newChild);
            return;
        }

        if(this._patternOverRule_ == oldChild)
        {
            setPatternOverRule((PPatternOverRule) newChild);
            return;
        }

        if(this._opRightSm_ == oldChild)
        {
            setOpRightSm((TOpRightSm) newChild);
            return;
        }

        if(this._opSemi_ == oldChild)
        {
            setOpSemi((TOpSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
