/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class ARangeRest extends PRangeRest
{
    private TOpMinus _opMinus_;
    private TNumber _number_;

    public ARangeRest()
    {
        // Constructor
    }

    public ARangeRest(
        @SuppressWarnings("hiding") TOpMinus _opMinus_,
        @SuppressWarnings("hiding") TNumber _number_)
    {
        // Constructor
        setOpMinus(_opMinus_);

        setNumber(_number_);

    }

    @Override
    public Object clone()
    {
        return new ARangeRest(
            cloneNode(this._opMinus_),
            cloneNode(this._number_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARangeRest(this);
    }

    public TOpMinus getOpMinus()
    {
        return this._opMinus_;
    }

    public void setOpMinus(TOpMinus node)
    {
        if(this._opMinus_ != null)
        {
            this._opMinus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opMinus_ = node;
    }

    public TNumber getNumber()
    {
        return this._number_;
    }

    public void setNumber(TNumber node)
    {
        if(this._number_ != null)
        {
            this._number_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._number_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opMinus_)
            + toString(this._number_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opMinus_ == child)
        {
            this._opMinus_ = null;
            return;
        }

        if(this._number_ == child)
        {
            this._number_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opMinus_ == oldChild)
        {
            setOpMinus((TOpMinus) newChild);
            return;
        }

        if(this._number_ == oldChild)
        {
            setNumber((TNumber) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
