/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class ASamePatternKeyword extends PPatternKeyword
{
    private TKeywordSame _keywordSame_;

    public ASamePatternKeyword()
    {
        // Constructor
    }

    public ASamePatternKeyword(
        @SuppressWarnings("hiding") TKeywordSame _keywordSame_)
    {
        // Constructor
        setKeywordSame(_keywordSame_);

    }

    @Override
    public Object clone()
    {
        return new ASamePatternKeyword(
            cloneNode(this._keywordSame_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASamePatternKeyword(this);
    }

    public TKeywordSame getKeywordSame()
    {
        return this._keywordSame_;
    }

    public void setKeywordSame(TKeywordSame node)
    {
        if(this._keywordSame_ != null)
        {
            this._keywordSame_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordSame_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordSame_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordSame_ == child)
        {
            this._keywordSame_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordSame_ == oldChild)
        {
            setKeywordSame((TKeywordSame) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
