/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class ASelfreplaceConfigKeyword extends PConfigKeyword
{
    private TKeywordSelfreplace _keywordSelfreplace_;

    public ASelfreplaceConfigKeyword()
    {
        // Constructor
    }

    public ASelfreplaceConfigKeyword(
        @SuppressWarnings("hiding") TKeywordSelfreplace _keywordSelfreplace_)
    {
        // Constructor
        setKeywordSelfreplace(_keywordSelfreplace_);

    }

    @Override
    public Object clone()
    {
        return new ASelfreplaceConfigKeyword(
            cloneNode(this._keywordSelfreplace_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASelfreplaceConfigKeyword(this);
    }

    public TKeywordSelfreplace getKeywordSelfreplace()
    {
        return this._keywordSelfreplace_;
    }

    public void setKeywordSelfreplace(TKeywordSelfreplace node)
    {
        if(this._keywordSelfreplace_ != null)
        {
            this._keywordSelfreplace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordSelfreplace_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordSelfreplace_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordSelfreplace_ == child)
        {
            this._keywordSelfreplace_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordSelfreplace_ == oldChild)
        {
            setKeywordSelfreplace((TKeywordSelfreplace) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
