/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class ASuitCompareRule extends PCompareRule
{
    private TOpSuit _opSuit_;

    public ASuitCompareRule()
    {
        // Constructor
    }

    public ASuitCompareRule(
        @SuppressWarnings("hiding") TOpSuit _opSuit_)
    {
        // Constructor
        setOpSuit(_opSuit_);

    }

    @Override
    public Object clone()
    {
        return new ASuitCompareRule(
            cloneNode(this._opSuit_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuitCompareRule(this);
    }

    public TOpSuit getOpSuit()
    {
        return this._opSuit_;
    }

    public void setOpSuit(TOpSuit node)
    {
        if(this._opSuit_ != null)
        {
            this._opSuit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opSuit_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opSuit_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opSuit_ == child)
        {
            this._opSuit_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opSuit_ == oldChild)
        {
            setOpSuit((TOpSuit) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
