/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class AWinValueConfigValue extends PConfigValue
{
    private PWinValue _winValue_;

    public AWinValueConfigValue()
    {
        // Constructor
    }

    public AWinValueConfigValue(
        @SuppressWarnings("hiding") PWinValue _winValue_)
    {
        // Constructor
        setWinValue(_winValue_);

    }

    @Override
    public Object clone()
    {
        return new AWinValueConfigValue(
            cloneNode(this._winValue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWinValueConfigValue(this);
    }

    public PWinValue getWinValue()
    {
        return this._winValue_;
    }

    public void setWinValue(PWinValue node)
    {
        if(this._winValue_ != null)
        {
            this._winValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._winValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._winValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._winValue_ == child)
        {
            this._winValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._winValue_ == oldChild)
        {
            setWinValue((PWinValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
