/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class AWinConfigKeyword extends PConfigKeyword
{
    private TKeywordWin _keywordWin_;

    public AWinConfigKeyword()
    {
        // Constructor
    }

    public AWinConfigKeyword(
        @SuppressWarnings("hiding") TKeywordWin _keywordWin_)
    {
        // Constructor
        setKeywordWin(_keywordWin_);

    }

    @Override
    public Object clone()
    {
        return new AWinConfigKeyword(
            cloneNode(this._keywordWin_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWinConfigKeyword(this);
    }

    public TKeywordWin getKeywordWin()
    {
        return this._keywordWin_;
    }

    public void setKeywordWin(TKeywordWin node)
    {
        if(this._keywordWin_ != null)
        {
            this._keywordWin_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._keywordWin_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._keywordWin_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._keywordWin_ == child)
        {
            this._keywordWin_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._keywordWin_ == oldChild)
        {
            setKeywordWin((TKeywordWin) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
