/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class TFuncDrawtoall extends Token
{
    public TFuncDrawtoall()
    {
        super.setText("drawToAll");
    }

    public TFuncDrawtoall(int line, int pos)
    {
        super.setText("drawToAll");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFuncDrawtoall(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFuncDrawtoall(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFuncDrawtoall text.");
    }
}
