/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class TFuncSetdisplaysize extends Token
{
    public TFuncSetdisplaysize()
    {
        super.setText("setDisplaySize");
    }

    public TFuncSetdisplaysize(int line, int pos)
    {
        super.setText("setDisplaySize");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFuncSetdisplaysize(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFuncSetdisplaysize(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFuncSetdisplaysize text.");
    }
}
