/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class TFuncDrawto extends Token
{
    public TFuncDrawto()
    {
        super.setText("drawTo");
    }

    public TFuncDrawto(int line, int pos)
    {
        super.setText("drawTo");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFuncDrawto(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFuncDrawto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFuncDrawto text.");
    }
}
