/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class TKerwordAfter extends Token
{
    public TKerwordAfter()
    {
        super.setText("after");
    }

    public TKerwordAfter(int line, int pos)
    {
        super.setText("after");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKerwordAfter(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKerwordAfter(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKerwordAfter text.");
    }
}
