/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class TKeywordSelfreplace extends Token
{
    public TKeywordSelfreplace()
    {
        super.setText("selfReplace");
    }

    public TKeywordSelfreplace(int line, int pos)
    {
        super.setText("selfReplace");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKeywordSelfreplace(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordSelfreplace(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKeywordSelfreplace text.");
    }
}
