/* This file was generated by SableCC (http://www.sablecc.org/). */

package card.node;

import card.analysis.*;

@SuppressWarnings("nls")
public final class TKeywordAddpattern extends Token
{
    public TKeywordAddpattern()
    {
        super.setText("addPattern");
    }

    public TKeywordAddpattern(int line, int pos)
    {
        super.setText("addPattern");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKeywordAddpattern(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKeywordAddpattern(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKeywordAddpattern text.");
    }
}
